### ISSUE TITLE
Icon change does not work

### ISSUE THREAD

**Issue by ghost** [jfcherng/Sublime-Portable-Tool#1]
I believe i did it correctly but it does nothing. I'm on Windows 10 20H2.

**Comment by jfcherng** [comment]
probably because of Windows' cache. any error message during executing the change?

**Comment by ghost** [comment]
Thanks for the reply. I was using installed Sublime Text. Then I uninstalled it and downloaded portable version. Your program works excellent with portable version. At first I thought it wouldn't make a difference if I have installed version.

**Comment by jfcherng** [comment]
> Thanks for the reply. I was using installed Sublime Text. Then I uninstalled it and downloaded portable version. Your program works excellent with portable version. At first I thought it wouldn't make a difference if I have installed version.

Hmm... it should work for installed version as well.
